version: 0.2
#env:
#  secrets-manager:
#    SECILL2: "secretname:mysecret"
env:
  parameter-store:
    SECILL: "myparameter"

phases:
  pre_build:
    commands:
      - echo rogue ${SECILL}
      - aws --version

  build:
    commands:
      - echo Building the Docker image...
      #- docker build -t secil:latest --build-arg VAR=${SECILL} .
      - docker build -t secil:latest .
  post_build:
    commands:
      - echo Build completed on `date`
